### ISSUE TITLE
Data set on training

### ISSUE THREAD

**Issue by zhubingerdai** [bluedream1121/Key.Net_PyTorch#1]
I was wondering where the training data set was downloaded from? I didn't understand the training... How are synthetic datasets generated??

**Comment by bluedream1121** [comment]
Hello. I use the validation set of ILSVRC2012.

You can download the dataset using this link: https://image-net.org/challenges/LSVRC/2012/

**Comment by zhubingerdai** [comment]
Thank you very much！















At 2021-09-21 17:36:50, "Jongmin Lee" ***@***.***> wrote:

Hello. I use the validation set of ILSVRC2012.

You can download the dataset using this link: https://image-net.org/challenges/LSVRC/2012/

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zhubingerdai** [comment]
I downloaded the data set, but there was this problem. The dataset contains ILSVRC2012_bbox_train_v2, ILSVRC2012_devkit_t12, train, val. I don't know what synth is?







 File "train.py", line 23, in <module>

    aux.check_directory(args.synth_dir)

  File "/home/szw/Key.Net_PyTorch-main/keyNet/aux/tools.py", line 32, in check_directory

    os.mkdir(file_path)

FileNotFoundError: [Errno 2] No such file or directory: 'datasets/synth/'

**Comment by bluedream1121** [comment]
--synth_dir option means your output directory of the generated synthetic data

**Comment by zhubingerdai** [comment]
ok.I run the command  ’python train.py --data-dir ImageNet‘ ， There are four folders in my ImageNet folder: ILSVRC2012_bbox_train_v2, ILSVRC2012_devkit_t12, train,and val. There may be something wrong with the dataset I downloaded, and the synthetic dataset is not generated.The problem is not solved.

**Comment by zhubingerdai** [comment]
I really feel confused. I also specified the Sysnth folder, but kept getting errors. Can I get a screenshot of your dataset file and synth_dir file? I can't seem to solve the problem. Thank you very much.
















At 2021-09-28 08:50:50, "Jongmin Lee" ***@***.***> wrote:

--synth_dir option means your output directory of the generated synthetic data

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zhubingerdai** [comment]
I really feel confused. I also specified the Sysnth folder, but kept getting errors. Can I get a screenshot of your dataset file and synth_dir file? I can't seem to solve the problem. Thank you very much.

**Comment by bluedream1121** [comment]
(torch1.7) jongmin@jongmin-All-Series:~/Desktop$ git clone https://github.com/bluedream1121/Key.Net_PyTorch
Cloning into 'Key.Net_PyTorch'...
remote: Enumerating objects: 43, done.
remote: Counting objects: 100% (43/43), done.
remote: Compressing objects: 100% (42/42), done.
remote: Total 43 (delta 6), reused 33 (delta 1), pack-reused 0
Unpacking objects: 100% (43/43), done.
(torch1.7) jongmin@jongmin-All-Series:~/Desktop$ cd Key.Net_PyTorch/
(torch1.7) jongmin@jongmin-All-Series:~/Desktop/Key.Net_PyTorch$ mkdir datasets
(torch1.7) jongmin@jongmin-All-Series:~/Desktop/Key.Net_PyTorch$ python train.py --data-dir ~/datasets/ImageNet2012/ILSVRC2012_img_val/

**Comment by zhubingerdai** [comment]
Is there a problem with my data set? I cut down a part of the data set to run the program，but there is a error also.

**Comment by bluedream1121** [comment]
You can refer the issue number 2 (https://github.com/bluedream1121/Key.Net_PyTorch/issues/2)
