### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/synth/'

### ISSUE THREAD

**Issue by zhubingerdai** [bluedream1121/Key.Net_PyTorch#2]
How to fix this error? The input command -------- "python train.py --data-dir /path/to/ImageNet"
I downloaded the data set, but I still don't know how to solve it? I sent an email earlier. Sorry to interrupt.

**Comment by bluedream1121** [comment]
--data-dir option means the downloaded imagenet challenge 2012 dataset folder directory. 

Then the synthetic dataset are saved to "--synth-dir" option directory.

**Comment by zhubingerdai** [comment]
ok.I run the command  ’python train.py --data-dir ImageNet‘ ， There are four folders in my ImageNet folder: ILSVRC2012_bbox_train_v2, ILSVRC2012_devkit_t12, train,and val. There may be something wrong with the dataset I downloaded, and the synthetic dataset is not generated.The problem is not solved.



 I also want to know where I can find the code and related articles of Tiny-Key.Net mentioned in your article？I can't find it in your references .I can't findTiny-Key.Net on the Internet。Where can I download this code and article?






















Looking forward to your reply










—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by bluedream1121** [comment]
You can use this command --data-dir is your absolute data path.

python train.py --data-dir ~/datasets/ImageNet2012/ILSVRC2012_img_val/
